[package]
name = "dep-mapper"
version = "0.1.0"
edition = "2024"

[dependencies]
rustpython-parser = "0.4"
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
petgraph = "0.8.2"
serde = { version = "1.0", features = ["derive"] }
walkdir = "2.5.0"
